### ISSUE TITLE
social icons 

### ISSUE THREAD

**Issue by woodsy751** [locii/zengridframework4-universal#17]
cant set position left or right  tried in xero

**Comment by locii** [comment]
Which position do you have the social icons published to?

**Comment by locii** [comment]
Under the social tab you need to set it to either fixed left or fixed right. And also the module it's assined to needs to be assigned to the debug position. I still have to fix a few things here because I can see how it can get confusing. Most positions will render them in the correct fixed position but if it's added to the above content position it may get trapped inside that div
